services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_forte
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - /home/ear/data/postgres:/var/lib/postgresql/data
    networks:
      - ai-net

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senha_forte
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
    volumes:
      - /home/ear/data/mysql:/var/lib/mysql
    networks:
      - ai-net

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /home/ear/data/redis:/data
    networks:
      - ai-net

networks:
  ai-net:
    external: true
