# Usa uma imagem base do Python 3.10
FROM python:3.10

# Define um diretório de trabalho dentro do container
WORKDIR /app

# Instala as dependências do sistema
RUN apt-get update && apt-get install -y git libsndfile1

# Clona o repositório do Bark
# RUN git clone https://github.com/suno-ai/bark.git .
RUN git clone https://github.com/JonathanFly/bark-gui.git .

# --- Alteração crucial ---
# Instala PyTorch e TorchAudio para CUDA 12.1/12.2.
# Isso garante que a versão da CUDA de ambas as bibliotecas seja a mesma.
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

# Instala as demais dependências do Bark.
RUN pip install .

# Adiciona a variável de ambiente para resolver o erro de pickle (necessário para versões mais novas do PyTorch)
ENV BARK_INSECURE_PYTORCH_PICKLE=1

# Baixa os modelos pré-treinados do Bark.
RUN python -c "from bark import generate_audio; generate_audio('model download check');"

# Expõe a porta 8000
EXPOSE 8000

# Define o comando padrão
CMD ["python", "app.py", "--listen"]