services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/ear/data/npm/data:/data
      - /home/ear/data/npm/letsencrypt:/etc/letsencrypt
    networks:
      - ai-net

networks:
  ai-net:
    external: true
