services:
  stable-diffusion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stable-diffusion
    restart: unless-stopped
    ports:
      - "7860:7860"
      - "7861:7861"
    volumes:
      - /home/ear/data/stable-diffusion/models:/app/models
      - /home/ear/data/stable-diffusion/outputs:/app/outputs
      - /home/ear/data/stable-diffusion/extensions:/app/extensions
      - /home/ear/data/stable-diffusion/embeddings:/app/embeddings
      - /home/ear/data/stable-diffusion/config:/app/config
    environment:
      - WEBUI_PORT=7860
      - API_PORT=7861
    networks:
      - ai-net
    user: "1000:1000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  ai-net:
    external: true